var ie=document.all?true:false,textbox,resultbox,cl,lang,user,uid,currenttitle,tab1,language,plugin_urls,loaded_plugins,unrendered,css_urls,currentWidth,haveindex=false;
function loading(){plugin_urls=[];loaded_plugins=[];css_urls=[];tree.clickhandler=clickhandler;lang="";tab1=tabs();tab1.create({name:"tabs",target:"tabdiv",width:"100%",height:"100%",info:[{label:"Contents",content:"ctab1",foc:""},{label:"Index",content:"ctab2",foc:""},{label:"Search",content:"ctab3",foc:"keyword"},{label:"Help",content:"ctab4",foc:""}]});tab1.tabs[0].onclick=tabchange;tab1.tabs[1].onclick=tabchange;if(readCookie("lang"))lang=readCookie("lang");languages();cl="tree"}
function clickhandler(a,b){handler="handlers/getpage.php?id="+parseInt(a)+"&lang="+lang;document.getElementById("help").innerHTML='<div style="margin:30px;"><img src="images/system/bigrotation2.gif"/></div>';ajax(handler,null,function(c){c=eval("("+c.responseText+")");var d=c.page;document.getElementById("help").innerHTML=Wiky.toHtml(d);b&&searchHighlight(document.getElementById("help").innerHTML);RedirectLocation("LocationAnchor",a,"#"+a);d=document.getElementById("edita");var e=document.getElementById("tagsm");
if(c.editable=="1"||c.editable=="2"){d.innerHTML=language.menu.edit;e.style.display="block"}else{if(language!=null)d.innerHTML=language.sourceview;e.style.display="none"}},"GET")}var updateLayout=function(){if(window.innerWidth!=currentWidth){currentWidth=window.innerWidth;document.body.setAttribute("orient",currentWidth==320?"profile":"landscape");window.scrollTo(0,1)}};function tabchange(){tab1.selected==0&&tree.updateNode(tree.activenode);tab1.selected==1&&!haveindex&&getindex()}
function printpage(){var a=document.getElementById("help").innerHTML;win=window.open("","mywindow","width=500,height=500");self.focus();win.document.open();win.document.write("<html><head><title>Help Page</title>");win.document.write("<link rel='stylesheet' type='text/css' href='theme/default/css/ui.css'><link></head>");win.document.write(a+"</body></html>");win.document.close();win.print();win.close()}function dummy(){}
function getindex(){ajax("handlers/getindex.php?lang="+lang,null,function(a){a=a.responseXML.documentElement.getElementsByTagName("tag");for(var b=document.getElementById("indexpane"),c="",d=0;d<a.length;d++){var e=a[d],f=e.getAttribute("label");c+="<div id='tag-"+f.replace(" ","_")+"' class='indextag'>"+f+"</div>";e=e.getElementsByTagName("node");for(var g=0;g<e.length;g++){var h=e[g],k=h.getAttribute("label");h=h.getAttribute("id");c+="<div style='margin-left:20px;'><a href='javascript:indexpage("+
h+',"'+f+"\")'>"+k+"</a></div>"}}b.innerHTML=c;haveindex=true},"GET")}function indexpage(a){a!=tree.activenode&&clickhandler(a);tree.updateNode(a);cl="index"}
function changelanguage(){var a=document.getElementById("langsel");lang=a.options[a.selectedIndex].value;if(lang!=""){a=new Date;a.setTime(a.getTime()+2592E6);document.cookie="lang="+lang+"; expires="+a.toGMTString();ajax("language/"+lang+".json",null,function(b){b=eval("("+b.responseText+")");tab1.setLabel(0,b.tabs.contents);tab1.setLabel(1,b.tabs.index);tab1.setLabel(2,b.tabs.search);document.getElementById("searchtype").innerHTML=b.tabs.type;document.getElementById("searchlist").value=b.tabs.list;
language=b;tree.getTree("handlers/gettree.php?lang="+lang,"tree");haveindex=false;tab1.selected==1&&getindex();document.getElementById("keyword").value="";document.getElementById("searchresult").innerHTML=""});return false}}
function languages(){ajax("language/languages.json",null,function(a){a=eval("("+a.responseText+")");for(var b="",c=0;c<a.languages.length;c++)b+="<option value='"+a.languages[c].symbol+"'>"+a.languages[c].text+"</option>";document.getElementById("lang").innerHTML='<select id="langsel" onchange="changelanguage();">'+b+"</select>";b=document.getElementById("langsel");if(lang=="")lang=a.languages[0].symbol;b.value=lang;changelanguage()});return false}
function getRequestObject(){var a=null;try{this.postmode=true;a=new XMLHttpRequest}catch(b){try{this.postmode=false;a=new ActiveXObject("Msxml2.XMLHTTP")}catch(c){a=new ActiveXObject("Microsoft.XMLHTTP")}}return a}
function search(){textbox=document.getElementById("keyword");resultbox=document.getElementById("searchresult");ajax("handlers/search.php?lang="+lang,"search="+encodeURIComponent(textbox.value),function(a){var b=a.responseXML.documentElement.getElementsByTagName("file"),c="";for(a=0;a<b.length;a++){var d=b[a];c+="<div class='list' onclick='searchClick(\""+d.getAttribute("name")+"\")'>"+d.getAttribute("title")+"</div>"}resultbox.innerHTML=c});return false}
function searchHighlight(a){for(var b=textbox.value.split(" "),c=0;c<b.length;c++){pattern="("+b[c]+")(?=[^>]*<)";a=a.replace(RegExp(pattern,"gi"),"<span style='background:yellow;display:inline-block;'>$1</span>")}document.getElementById("help").innerHTML=a}function searchClick(a){a!=tree.activenode?clickhandler(a,true):searchHighlight(document.getElementById("help").innerHTML);tree.updateNode(a);cl="search"}
function plugins(){unrendered=[];for(var a in Wiky.plugins){var b=Wiky.plugins[a];unrendered.push(b);var c="plugins/"+b[0]+"/"+b[0]+".js";loadPlugin(c,b);ArrayContains(loaded_plugins,c)&&renderplugin(b)}}function clone(a){var b=function(){};b.prototype=a;return new b}function renderplugin(a){try{var b=eval("("+a[0].replace("-","_")+")"),c=clone(b);c.init(a[1],a[2]);c.render();ArrayRemove(unrendered,a)}catch(d){}}
function updateplugins(a){loaded_plugins.push(a);for(a=unrendered.length-1;a>-1;a--){var b=unrendered[a];ArrayContains(loaded_plugins,"plugins/"+b[0]+"/"+b[0]+".js")&&renderplugin(b)}}
function loadPlugin(a){if(!ArrayContains(plugin_urls,a)){plugin_urls.push(a);var b=document.createElement("script");b.src=a;b.type="text/javascript";if(b.readyState)b.onreadystatechange=function(){if(b.readyState=="loaded"||b.readyState=="complete"){b.onreadystatechange=null;updateplugins(a)}};else b.onload=function(){updateplugins(a)};document.getElementsByTagName("head")[0].appendChild(b)}}var last="";
function CheckForHash(){if(document.location.hash){var a=document.location.hash;a=a.substring(1);if(last==a)return;parseInt(a)!=tree.activenode&&tree.activenode!=""&&tree.click(a);var b=a.split("-");if(b.length>1)if(b[1].substring(0,2)!=lang){a=document.getElementById("langsel");for(i=0;i<a.length;i++)if(a[i].value==b[1].substring(0,2)){a.selectedIndex=i;break}lang=b[1].substring(0,2);changelanguage();return}anchor(a);tab1.setTab(3);last=a}updateLayout()}
function RenameAnchor(a,b){document.getElementById(a).name=b}function RedirectLocation(a,b,c){var d=c.split("-"),e=b.toString().split("#");e=e.length>1?"#"+e[1]:"";RenameAnchor(a,b);document.location.hash=d[0]+"-"+lang+e;plugins();anchor(c)}function anchor(a){anum=a.substring(1);a=document.body;a.scrollTop=0;if(parseInt(anum)!=anum){var b=anum.split("%23");if(b.length>1){b=document.getElementsByName(b[1]);if(b.length>0)a.scrollTop=b[0].offsetTop+80}}}function forward(){history.go(1)}
function back(){history.go(-1)}function readCookie(a){a=a+"=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(a)==0)return d.substring(a.length,d.length)}return null}function pageFromPath(a){ajax("handlers/pageFromPath.php","lang="+lang+"&path="+encodeURIComponent(a),function(b){b=b.responseText.replace(/^\s+|\s+$/g,"");if(b>0)tree.click(b);else b==-1&&edit(a)})}
function ajax(a,b,c,d){if(d==null)d="POST";var e=getRequestObject();e.onreadystatechange=function(){e.readyState==4&&c(e)};e.open(d,a,true);d=="POST"&&e.setRequestHeader("Content-type","application/x-www-form-urlencoded");e.send(b)}
function updatefldrfrm(a){var b=document.getElementById("fldrfrmname"),c=document.getElementById("fldrfrmaddpaste"),d=document.getElementById("fldrfrmcmt");if(a.id=="faddpage"){b.style.display="block";c.style.display="block";d.style.display="block"}if(a.id=="fremovefolder"){b.style.display="none";c.style.display="none";d.style.display="block"}if(a.id=="fcut"){b.style.display="none";c.style.display="none";d.style.display="none"}if(a.id=="fpaste"){b.style.display="none";c.style.display="block";d.style.display=
"block"}if(a.id=="frename"){b.style.display="block";c.style.display="none";d.style.display="block"}}function ArrayContains(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)return true;return false}function ArrayRemove(a,b){for(var c=0;c<a.length;c++)a[c]==b&&a.splice(c,1)}var HashCheckInterval=setInterval("CheckForHash()",250);var tree={n:0,target:null,clickhandler:null,home:"",nodes:[],crumbs:[],activenode:"",activetitle:"",highlight:"#ccccff",normal:"#ffffff",updateNode:function(a){if(a&&this.nodes.length>0){a=parseInt(a);this.crumbs=[];this.expandnode(this.nodes[a]);this.crumbs.reverse();if(a in this.nodes){if(this.activenode!="")document.getElementById(this.nodes[this.activenode].id).style.backgroundColor=this.normal;this.activenode=a;this.activetitle=this.nodes[a].label;a=document.getElementById(this.nodes[a].id);
a.style.backgroundColor=this.highlight;var b=a.parentNode.parentNode,c=document.getElementById("toc");if(b.offsetTop-c.scrollTop+a.offsetHeight>c.offsetHeight)c.scrollTop=b.offsetTop+a.offsetHeight-c.offsetHeight;if(c.scrollTop>b.offsetTop)c.scrollTop=b.offsetTop}}},click:function(a){this.clickhandler(a);this.updateNode(a);cl="tree"},getTree:function(a,b,c){this.nodes=[];this.home="";this.activenode=c==null?"":c;this.target=document.getElementById(b);var d=this;ajax(a,null,function(e){e=e.responseXML.documentElement;
d.target.innerHTML="";tree.parseTree(e,d.target,0);if(document.location.hash)d.activenode==""&&!document.location.hash.substring(1)in d.nodes?tree.click(tree.home):tree.click(document.location.hash.substring(1));else tree.click(tree.home)},"GET",false)},parseTree:function(a,b,c){for(var d=0;d<a.childNodes.length;d++){var e=a.childNodes[d];if(e.nodeName=="folder"){if(this.home=="")this.home=e.getAttribute("ref");this.n++;var f=document.createElement("div");f.className="node";var g="<div style='overflow:hidden;width:1000px;'><div class='toggle closed' id='toggle"+
e.getAttribute("ref")+"' onclick='tree.togglenode("+e.getAttribute("ref")+")'></div><div id='treelabel"+e.getAttribute("ref")+"' class='closelabel' onclick='tree.click(\""+e.getAttribute("ref")+"\");' onselectstart='return false;' ondblclick='tree.togglenode("+e.getAttribute("ref")+")'>"+e.getAttribute("label")+"</div></div>",h=document.createElement("div");h.id="treenode"+e.getAttribute("ref");f.innerHTML=g;f.appendChild(h);h.style.display="none";if(e.getAttribute("ref")!="")this.nodes[e.getAttribute("ref")]=
{ref:e.getAttribute("ref"),id:"treelabel"+e.getAttribute("ref"),label:e.getAttribute("label"),pid:b.id,owner:c};this.parseTree(e,h,e.getAttribute("ref"));b.appendChild(f)}if(e.nodeName=="leaf"){if(this.home=="")this.home=e.getAttribute("ref");this.n++;f=document.createElement("div");f.innerHTML="<div style='overflow:hidden;width:1000px;'><div id='treelabel"+e.getAttribute("ref")+"' class='leaf' onclick='tree.click(\""+e.getAttribute("ref")+"\");' onselectstart='return false;'>"+e.getAttribute("label")+
"</div></div>";f.getAttribute("ref");b.appendChild(f);if(e.getAttribute("ref")!="")this.nodes[e.getAttribute("ref")]={id:"treelabel"+e.getAttribute("ref"),label:e.getAttribute("label"),pid:b.id,owner:c}}}},togglenode:function(a){var b=document.getElementById("treenode"+a),c=document.getElementById("treelabel"+a);a=document.getElementById("toggle"+a);if(b.style.display=="block"){b.style.display="none";c.className="closelabel";a.className="toggle closed"}else{b.style.display="block";c.className="nodelabel";
a.className="toggle open"}},expandnode:function(a){if(a){this.crumbs.push(a);if(a.owner!=0){var b=document.getElementById(a.pid),c=a.pid.substring(8),d=document.getElementById("treelabel"+c);c=document.getElementById("toggle"+c);b.style.display="block";d.className="nodelabel";c.className="toggle open";this.expandnode(this.nodes[a.owner])}}}};var tabs=function(){return{info:null,target:null,name:null,height:null,width:null,tabs:[],selected:0,getLabel:function(a){return this.tabs[a].innerHTML},setLabel:function(a,b){this.tabs[a].innerHTML=b},setTab:function(a){for(var b=0;b<this.info.length;b++){var c=this.tabs[b],d=document.getElementById(this.info[b].content);if(a==b){c.className="tabon";d.style.display="block";this.info[b].foc!=""&&document.getElementById(this.info[b].foc).focus()}else{d.style.display="none";c.className="taboff"}}},
remove:function(a){this.tabs.splice(a,1);this.info.splice(a,1);this.target.removeChild(document.getElementById(this.name+"tab"+a))},create:function(a){this.target=document.getElementById(a.target);this.info=a.info;this.name=a.name;this.height=a.height;this.width=a.width;this.target.style.height=this.height;for(a=0;a<this.info.length;a++){var b=document.createElement("div");b.setAttribute("id",this.name+"tab"+a);b.className="taboff";b.innerHTML=this.info[a].label;var c=this;b.onmouseup=function(){for(var e=
0;e<c.info.length;e++){var f=c.tabs[e],g=document.getElementById(c.info[e].content);if(f==this){f.className="tabon";g.style.display="block";c.info[e].foc!=""&&document.getElementById(c.info[e].foc).focus();c.selected=e}else{g.style.display="none";f.className="taboff"}}};b.style.height="22px";this.tabs[a]=b;this.target.appendChild(b);var d=document.getElementById(this.info[a].content);d.style.left=0;d.style.display="none";d.style.top=b.offsetHeight-1+"px"}this.tabs[0].className="tabon";document.getElementById(this.info[0].content).style.display=
"block"}}};var Wiky={version:0.95,blocks:null,plugins:null,rules:{all:["Wiky.rules.pre","Wiky.rules.nonwikiblocks","Wiky.rules.wikiblocks"],pre:[{rex:/(\r?\n)/g,tmplt:"\u00b6"}],post:[{rex:/(^\xB6)|(\xB6$)/g,tmplt:""},{rex:/@([0-9]+)@/g,tmplt:function(a,b){return Wiky.restore(b)}},{rex:/\xB6/g,tmplt:"\n"}],nonwikiblocks:[{rex:/\\([%])/g,tmplt:function(a,b){return Wiky.store(b)}},{rex:/\[%(.*?)%\]/g,tmplt:function(a,b){return Wiky.store("<pre>"+Wiky.apply(b,Wiky.rules.code)+"</pre>")+"[p:"}}],wikiblocks:["Wiky.rules.nonwikiinlines",
"Wiky.rules.escapes",{rex:/(?:^|\xB6)(={1,6})(.*?)[=]*(?=\xB6|$)/g,tmplt:function(a,b,c){a=b.length;return":p]\u00b6<h"+a+">"+c+"</h"+a+">\u00b6[p:"}},{rex:/(?:^|\xB6)[-]{4}(?:\xB6|$)/g,tmplt:"\u00b6<hr/>\u00b6"},{rex:/\\\\([ \xB6])/g,tmplt:"<br/>$1"},{rex:/`(?:\{(.*?)\})([^`]+)`/g,tmplt:function(a,b,c){return Wiky.store("<span"+Wiky.style(b)+">"+c+"</span>")}},{rex:/(^|\xB6)([*01aAiIg]*[\.*])[ ]/g,tmplt:function(a,b,c){a=c.replace(/([*])/g,"u").replace(/([\.])/,"");return":"+a+"]"+b+"["+a+":"}},
{rex:/(?:^|\xB6);[ ](.*?):[ ]/g,tmplt:"\u00b6:l][l:$1:d][d:"},{rex:/\[(?:\{([^}]*)\})?(?:\(([^)]*)\))?\"/g,tmplt:function(a,b,c){return":p]<blockquote"+Wiky.attr(c,"cite",0)+Wiky.attr(c,"title",1)+Wiky.style(b)+">[p:"}},{rex:/\"\]/g,tmplt:":p]</blockquote>[p:"},{rex:/\[(\{[^}]*\})?\|/g,tmplt:":t]$1[r:"},{rex:/\|\]/g,tmplt:":r][t:"},{rex:/\|\xB6[ ]?\|/g,tmplt:":r]\u00b6[r:"},{rex:/\|/g,tmplt:":c][c:"},{rex:/^(.*)$/g,tmplt:"[p:$1:p]"},{rex:/(([\xB6])([ \t\f\v\xB6]*?)){2,}/g,tmplt:":p]$1[p:"},{rex:/\[([01AIacdgilprtu]+)[:](.*?)[:]([01AIacdgilprtu]+)\]/g,
tmplt:function(a,b,c,d){return Wiky.sectionRule(b==undefined?"":b,"",Wiky.apply(c,Wiky.rules.wikiinlines),!d?"":d)}},{rex:/\[[01AIacdgilprtu]+[:]|[:][01AIacdgilprtu]+\]/g,tmplt:""},{rex:/<td>(?:([0-9]*)[>])?([ ]?)(.*?)([ ]?)<\/td>/g,tmplt:function(a,b,c,d,e){return"<td"+(b?' colspan="'+b+'"':"")+(c==" "?' style="text-align:'+(c==e?"center":"right")+';"':e==" "?' style="text-align:left;"':"")+">"+c+d+e+"</td>"}},{rex:/<(p|table|h[1-6])>(?:\xB6)?(?:\{(.*?)\})/g,tmplt:function(a,b,c){return Wiky.store("<"+
b+Wiky.style(c)+">")}},{rex:/<p>([ \t\f\v\xB6]*?)<\/p>/g,tmplt:"$1"},"Wiky.rules.shortcuts"],nonwikiinlines:[{rex:/%(?:\{([^}]*)\})?(?:\(([^)]*)\))?(.*?)%/g,tmplt:function(a,b,c,d){return Wiky.store("<code"+(c?' lang="x-'+Wiky.attr(c)+'"':"")+Wiky.style(b)+">"+Wiky.apply(d,c?Wiky.rules.lang[Wiky.attr(c)]:Wiky.rules.code)+"</code>")}},{rex:/%(.*?)%/g,tmplt:function(){return Wiky.store("<code>"+Wiky.apply($2,Wiky.rules.code)+"</code>")}}],wikiinlines:[{rex:/\*([^*]+)\*/g,tmplt:"<strong>$1</strong>"},
{rex:/\(\+(.+?)\+\)/g,tmplt:"<ins>$1</ins>"},{rex:/_([^_]+)_/g,tmplt:"<em>$1</em>"},{rex:/\^([^^]+)\^/g,tmplt:"<sup>$1</sup>"},{rex:/~([^~]+)~/g,tmplt:"<sub>$1</sub>"},{rex:/\(-(.+?)-\)/g,tmplt:"<del>$1</del>"},{rex:/\?([^ \t\f\v\xB6]+)\((.+)\)\?/g,tmplt:'<abbr title="$2">$1</abbr>'},{rex:/\[(?:\{([^}]*)\})?[Ii]ma?ge?\:([^ ,\]]*)(?:[, ]([^\]]*))?\]/g,tmplt:function(a,b,c,d){return Wiky.store("<img"+Wiky.style(b)+' src="'+c+'" alt="'+(d?d:c)+'" title="'+(d?d:c)+'"/>')}},{rex:/#\]/g,tmplt:"</div>"},
{rex:/\[#\s*([^ ,]+)[, ]([^\]]*);/g,tmplt:function(a,b,c){return Wiky.plug(b,c)}},{rex:/\[(\/[a-zA-z0-9_\u00A1-\uFFFF\-\/]+)\]/g,tmplt:function(a,b){return Wiky.store("<a href=\"javascript:pageFromPath('"+b+"');\">"+Wiky.word(b)+"</a>")}},{rex:/\[(http(s?)\:\/\/[^ ,]+)[, ]([^\]]*)\]/g,tmplt:function(a,b,c,d){return Wiky.store("<a class='extlink' href=\""+b+'">'+d+"</a>")}},{rex:/\[([^ ,]+)[, ]([^\]]*)\]/g,tmplt:function(a,b,c){return Wiky.store('<a href="'+b+'">'+c+"</a>")}},{rex:/(((http(s?))\:\/\/)?[A-Za-z0-9\._\/~\-: ]+\.(?:png|jpg|jpeg|gif|bmp))/gi,
tmplt:function(a,b){return Wiky.store('<img src="'+b+'" alt="'+b+'"/>')}},{rex:/((mailto\:|javascript\:|(news|file|(ht|f)tp(s?))\:\/\/)[A-Za-z0-9\.:_\/~%\-+&#?!=()@\x80-\xB5\xB7\xFF]+)/g,tmplt:'<a href="$1">$1</a>'}],escapes:[{rex:/\\([|*_~\^])/g,tmplt:function(a,b){return Wiky.store(b)}},{rex:/\\&/g,tmplt:"&amp;"},{rex:/\\>/g,tmplt:"&gt;"},{rex:/\\</g,tmplt:"&lt;"}],shortcuts:[{rex:/---/g,tmplt:"&#8212;"},{rex:/--/g,tmplt:"&#8211;"},{rex:/[\.]{3}/g,tmplt:"&#8230;"},{rex:/<->/g,tmplt:"&#8596;"},{rex:/<-/g,
tmplt:"&#8592;"},{rex:/->/g,tmplt:"&#8594;"}],code:[{rex:/&/g,tmplt:"&amp;"},{rex:/</g,tmplt:"&lt;"},{rex:/>/g,tmplt:"&gt;"}],lang:{}},toHtml:function(a){Wiky.blocks=[];Wiky.plugins=[];return Wiky.apply(Wiky.sanitize(Wiky.apply(a,Wiky.rules.all)),Wiky.rules.post)},apply:function(a,b){if(a&&b)for(var c in b)a=typeof b[c]=="string"?Wiky.apply(a,eval(b[c])):a.replace(b[c].rex,b[c].tmplt);return a},plug:function(a,b){var c=eval("("+b+")"),d=a+"_"+Wiky.plugins.length;Wiky.plugins.push([a,d,c]);return"<div id='"+
d+"'>"},sanitize:function(a){var b=document.createElement("div");b.innerHTML=a;a=b.getElementsByTagName("*");for(var c=a.length-1;c>-1;c--){var d=a.item(c),e=d.tagName.toLowerCase();if(e=="object"||e=="iframe"||e=="embed")d.parentNode.removeChild(d);else{if(d.style.position=="absolute"||d.style.position=="relative")d.style.position="static";e=d.attributes;for(var f=e.length-1;f>-1;f--){var g=e[f].name;g.indexOf("on")==0&&d.removeAttribute(g)}}}return b.innerHTML},store:function(a,b){return b?"@"+
(Wiky.blocks.push(a)-1)+"@":"@"+(Wiky.blocks.push(a.replace(/@([0-9]+)@/g,function(c,d){return Wiky.restore(d)}))-1)+"@"},restore:function(a){return Wiky.blocks[a]},attr:function(a,b,c){return(a=a&&a.split(",")[c||0])?b?" "+b+'="'+a+'"':a:""},hasAttr:function(a,b){return RegExp(b+"=").test(a)},attrVal:function(a,b){return a.replace(RegExp("^.*?"+b+'="(.*?)".*?$'),"$1")},invAttr:function(a,b){var c=[];for(var d in b)a.indexOf(b[d]+"=")>=0&&c.push(a.replace(RegExp("^.*?"+b[d]+'="(.*?)".*?$'),"$1"));
return c.length?"("+c.join(",")+")":""},style:function(a){a=a&&a.split(/,|;/);var b,c="";for(var d in a)if(a[d]!=null){b=a[d].split(":");c+=b[0]==">"?"margin-left:4em;":b[0]=="<"?"margin-right:4em;":b[0]==">>"?"float:right;":b[0]=="<<"?"float:left;":b[0]=="="?"display:block;margin:0 auto;":b[0]=="_"?"text-decoration:underline;":b[0]=="b"?"border:solid 1px;":b[0]=="c"?"color:"+b[1]+";":b[0]=="C"?"background:"+b[1]+";":b[0]=="w"?"width:"+b[1]+";":b[0]+":"+b[1]+";"}return c?' style="'+c+'"':""},invStyle:function(a){a=
(a=/style=/.test(a)?a.replace(/^.*?style=\"(.*?)\".*?$/,"$1"):"")&&a.split(";");var b,c=[];for(var d in a){b=a[d].split(":");if(b[0]=="margin-left"&&b[1]=="4em")c.push(">");else if(b[0]=="margin-right"&&b[1]=="4em")c.push("<");else if(b[0]=="float"&&b[1]=="right")c.push(">>");else if(b[0]=="float"&&b[1]=="left")c.push("<<");else if(b[0]=="margin"&&b[1]=="0 auto")c.push("=");else if(b[0]=="text-decoration"&&b[1]=="underline")c.push("_");else if(b[0]=="border"&&b[1]=="solid 1px")c.push("b");else if(b[0]==
"color")c.push("c:"+b[1]);else if(b[0]=="background")c.push("C:"+b[1]);else if(b[0]=="width")c.push("w:"+b[1]);else b[0]&&c.push(b[0]+":"+b[1])}return c.length?"{"+c.join(",")+"}":""},sectionRule:function(a,b,c,d){b={p_p:"<p>$1</p>",p_u:"<p>$1</p><ul$3>",p_o:"<p>$1</p><ol$3>",u_p:"<li$2>$1</li></ul>",u_c:"<li$2>$1</li></ul></td>",u_r:"<li$2>$1</li></ul></td></tr>",uu_p:"<li$2>$1</li></ul></li></ul>",uo_p:"<li$2>$1</li></ol></li></ul>",uuu_p:"<li$2>$1</li></ul></li></ul></li></ul>",uou_p:"<li$2>$1</li></ul></li></ol></li></ul>",
uuo_p:"<li$2>$1</li></ol></li></ul></li></ul>",uoo_p:"<li$2>$1</li></ol></li></ol></li></ul>",u_u:"<li$2>$1</li>",uu_u:"<li$2>$1</li></ul></li>",uo_u:"<li$2>$1</li></ol></li>",uuu_u:"<li$2>$1</li></ul></li></ul></li>",uou_u:"<li$2>$1</li></ul></li></ol></li>",uuo_u:"<li$2>$1</li></ol></li></ul></li>",uoo_u:"<li$2>$1</li></ol></li></ol></li>",u_uu:"<li$2>$1<ul$3>",u_o:"<li$2>$1</li></ul><ol$3>",uu_o:"<li$2>$1</li></ul></li></ul><ol$3>",uo_o:"<li$2>$1</li></ol></li></ul><ol$3>",uuu_o:"<li$2>$1</li></ul></li></ul></li></ul><ol$3>",
uou_o:"<li$2>$1</li></ul></li></ol></li></ul><ol$3>",uuo_o:"<li$2>$1</li></ol></li></ul></li></ul><ol$3>",uoo_o:"<li$2>$1</li></ol></li></ol></li></ul><ol$3>",u_uo:"<li$2>$1<ol$3>",o_p:"<li$2>$1</li></ol>",oo_p:"<li$2>$1</li></ol></li></ol>",ou_p:"<li$2>$1</li></ul></li></ol>",ooo_p:"<li$2>$1</li></ol></li></ol>",ouo_p:"<li$2>$1</li></ol></li></ul></li></ol>",oou_p:"<li$2>$1</li></ul></li></ol></li></ol>",ouu_p:"<li$2>$1</li></ul></li></ul></li></ol>",o_u:"<li$2>$1</li></ol><ul$3>",oo_u:"<li$2>$1</li></ol></li></ol><ul$3>",
ou_u:"<li$2>$1</li></ul></li></ol><ul$3>",ooo_u:"<li$2>$1</li></ol></li></ol></li></ol><ul$3>",ouo_u:"<li$2>$1</li></ol></li></ul></li></ol><ul$3>",oou_u:"<li$2>$1</li></ul></li></ol></li></ol><ul$3>",ouu_u:"<li$2>$1</li></ul></li></ul></li></ol><ul$3>",o_ou:"<li$2>$1<ul$3>",o_o:"<li$2>$1</li>",oo_o:"<li$2>$1</li></ol></li>",ou_o:"<li$2>$1</li></ul></li>",ooo_o:"<li$2>$1</li></ol></li></ol></li>",ouo_o:"<li$2>$1</li></ol></li></ul></li>",oou_o:"<li$2>$1</li></ul></li></ol></li>",ouu_o:"<li$2>$1</li></ul></li></ul></li>",
o_oo:"<li$2>$1<ol$3>",l_d:"<dt>$1</dt>",d_l:"<dd>$1</dd>",d_u:"<dd>$1</dd></dl><ul>",d_o:"<dd>$1</dd></dl><ol>",p_l:"<p>$1</p><dl>",u_l:"<li$2>$1</li></ul><dl>",o_l:"<li$2>$1</li></ol><dl>",uu_l:"<li$2>$1</li></ul></li></ul><dl>",uo_l:"<li$2>$1</li></ol></li></ul><dl>",ou_l:"<li$2>$1</li></ul></li></ol><dl>",oo_l:"<li$2>$1</li></ol></li></ol><dl>",d_p:"<dd>$1</dd></dl>",p_t:"<p>$1</p><table>",p_r:"<p>$1</p></td></tr>",p_c:"<p>$1</p></td>",t_p:"</table><p>$1</p>",r_r:"<tr><td>$1</td></tr>",r_p:"<tr><td><p>$1</p>",
r_c:"<tr><td>$1</td>",r_u:"<tr><td>$1<ul>",c_p:"<td><p>$1</p>",c_r:"<td>$1</td></tr>",c_c:"<td>$1</td>",u_t:"<li$2>$1</li></ul><table>",o_t:"<li$2>$1</li></ol><table>",d_t:"<dd>$1</dd></dl><table>",t_u:"</table><p>$1</p><ul>",t_o:"</table><p>$1</p><ol>",t_l:"</table><p>$1</p><dl>"};for(var e="",f="",g=Math.max(a.length,d.length),h=true,k={"0":"decimal-leading-zero","1":"decimal",a:"lower-alpha",A:"upper-alpha",i:"lower-roman",I:"upper-roman",g:"lower-greek"}[d.charAt(d.length-1)],j=0;j<g;j++)if(a.charAt(j+
1)!=d.charAt(j+1)||!h||j==g-1){e+=a.charAt(j)==undefined?" ":a.charAt(j);f+=d.charAt(j)==undefined?" ":d.charAt(j);h=false}d=(e+"_"+f).replace(/([01AIagi])/g,"o");return!b[d]?"?("+d+")":b[d].replace(/\$2/,' class="'+a+'"').replace(/\$3/,!k?"":' style="list-style-type:'+k+';"').replace(/\$1/,c).replace(/<p><\/p>/,"")},word:function(a){a=a.split("/");return a[a.length-1].replace(/([a-z])([A-Z])/g,"$1 $2")}};
